export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/1.jpeg",
    username: "Safak Kocaoglu",
  },
  {
    id: 2,
    profilePicture: "assets/person/2.jpeg",
    username: "Janell Shrum",
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpeg",
    username: "Alex Durden",
  },
  {
    id: 4,
    profilePicture: "assets/person/4.jpeg",
    username: "Dora Hawks",
  },
  {
    id: 5,
    profilePicture: "assets/person/5.jpeg",
    username: "Thomas Holden",
  },
  {
    id: 6,
    profilePicture: "assets/person/6.jpeg",
    username: "Shirley Beauchamp",
  },
  {
    id: 7,
    profilePicture: "assets/person/7.jpeg",
    username: "Travis Bennett",
  },
  {
    id: 8,
    profilePicture: "assets/person/8.jpeg",
    username: "Kristen Thomas",
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpeg",
    username: "Gary Duty",
  },
  {
    id: 10,
    profilePicture: "assets/person/10.jpeg",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];

export const Players = [
  {
    _id: "2544",
    name: "LeBron James",
    teamId: "1610612739",
    jersey: "23",
    pos: "F",
    heightFeet: 6,
    heightInches: 8,
    weightPounds: 250,
    age: 37,
    country: "USA",
    ppg: 29.9,
    apg: 4.5,
    rpg: 11.6,
    spg: 0.8,
    bpg: 1.1,
    fpg: 51.8,
  },
  {
    _id: "1629630",
    name: "Ja Morant",
    teamId: "1610612739",
    jersey: "12",
    pos: "G",
    heightFeet: 6,
    heightInches: 0,
    weightPounds: 175,
    age: 22,
    country: "USA",
    ppg: 25.6,
    apg: 6.7,
    rpg: 3.5,
    spg: 0.9,
    bpg: 0.1,
    fpg: 43.2,
  },
  {
    _id: "203109",
    name: "Jae Crowder",
    teamId: "1610612738",
    jersey: "99",
    pos: "F",
    heightFeet: 6,
    heightInches: 6,
    weightPounds: 235,
    age: 34,
    country: "USA",
    ppg: 14.3,
    apg: 3.5,
    rpg: 4.6,
    spg: 0.5,
    bpg: 0.4,
    fpg: 23.1,
  },
  {
    _id: "203507",
    name: "Giannis Antetokounmpo",
    teamId: "1610612749",
    jersey: "34",
    pos: "F",
    heightFeet: 6,
    heightInches: 11,
    weightPounds: 242,
    age: 27,
    country: "Greece",
    ppg: 29.6,
    apg: 5.7,
    rpg: 13.8,
    spg: 0.9,
    bpg: 1.5,
    fpg: 56.3,
  },
  {
    _id: "203507",
    name: "Giannis Antetokounmpo",
    teamId: "1610612749",
    jersey: "34",
    pos: "F",
    heightFeet: 6,
    heightInches: 11,
    weightPounds: 242,
    age: 27,
    country: "Greece",
    ppg: 29.6,
    apg: 5.7,
    rpg: 13.8,
    spg: 0.9,
    bpg: 1.5,
    fpg: 56.3,
  },
  {
    _id: "203507",
    name: "Giannis Antetokounmpo",
    teamId: "1610612749",
    jersey: "34",
    pos: "F",
    heightFeet: 6,
    heightInches: 11,
    weightPounds: 242,
    age: 27,
    country: "Greece",
    ppg: 29.6,
    apg: 5.7,
    rpg: 13.8,
    spg: 0.9,
    bpg: 1.5,
    fpg: 56.3,
  },
];
